/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/app/Header.vue')['default']
    AppNotificationView: typeof import('./../src/components/app/NotificationView.vue')['default']
    BaseBtnExpand: typeof import('./../src/components/base/btn/Expand.vue')['default']
    BaseOverlayProvider: typeof import('./../src/components/base/OverlayProvider.vue')['default']
    copy: typeof import('./../src/components/timeEntry/feature/create/Menu copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeEntryFeatureCreate: typeof import('./../src/components/timeEntry/feature/Create.vue')['default']
    TimeEntryFeatureCreateDialog: typeof import('./../src/components/timeEntry/feature/create/Dialog.vue')['default']
    TimeEntryFeatureCreateMenu: typeof import('./../src/components/timeEntry/feature/create/Menu.vue')['default']
    TimeEntryFeatureDelete: typeof import('./../src/components/timeEntry/feature/Delete.vue')['default']
    TimeEntryFeatureEdit: typeof import('./../src/components/timeEntry/feature/Edit.vue')['default']
    TimeEntryFeatureOverlayProvider: typeof import('./../src/components/timeEntry/feature/OverlayProvider.vue')['default']
    TimeEntryFeatureProvider: typeof import('./../src/components/timeEntry/feature/FeatureProvider.vue')['default']
    TimeEntryFieldTaskId: typeof import('./../src/components/timeEntry/field/TaskId.vue')['default']
    TrackingCalendarFeaturesConflictDialog: typeof import('./../src/components/tracking/calendar/features/ConflictDialog.vue')['default']
    TrackingCalendarFeaturesConflictOverlay: typeof import('./../src/components/tracking/calendar/features/ConflictOverlay.vue')['default']
    TrackingCalendarFeaturesCreateEventDialog: typeof import('./../src/components/tracking/calendar/features/CreateEventDialog.vue')['default']
    TrackingCalendarFeaturesCreateOverlay: typeof import('./../src/components/tracking/calendar/features/CreateOverlay.vue')['default']
    TrackingCalendarFeaturesDeleteEventDialog: typeof import('./../src/components/tracking/calendar/features/DeleteEventDialog.vue')['default']
    TrackingCalendarFeaturesDeleteOverlay: typeof import('./../src/components/tracking/calendar/features/DeleteOverlay.vue')['default']
    TrackingCalendarFeaturesEditEventDialog: typeof import('./../src/components/tracking/calendar/features/EditEventDialog.vue')['default']
    TrackingCalendarFeaturesEditOverlay: typeof import('./../src/components/tracking/calendar/features/EditOverlay.vue')['default']
    TrackingCalendarSidebar: typeof import('./../src/components/tracking/calendar/Sidebar.vue')['default']
    TrackingCalendarView: typeof import('./../src/components/tracking/calendar/View.vue')['default']
    TrackingFeatureMenuCreate: typeof import('./../src/components/tracking/feature/menu/Create.vue')['default']
    TrackingListFeaturesCreateOverlay: typeof import('./../src/components/tracking/list/features/CreateOverlay.vue')['default']
    TrackingListFeaturesDeleteOverlay: typeof import('./../src/components/tracking/list/features/DeleteOverlay.vue')['default']
    TrackingListFeaturesEditOverlay: typeof import('./../src/components/tracking/list/features/EditOverlay.vue')['default']
    TrackingListView: typeof import('./../src/components/tracking/list/View.vue')['default']
    TrackingToolbar: typeof import('./../src/components/tracking/Toolbar.vue')['default']
    VRowSingle: typeof import('./../src/components/VRowSingle.vue')['default']
  }
}
