/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../src/components/app/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackingCalendarFeaturesConflictDialog: typeof import('./../src/components/tracking/calendar/features/ConflictDialog.vue')['default']
    TrackingCalendarFeaturesCreateDialog: typeof import('./../src/components/tracking/calendar/features/CreateDialog.vue')['default']
    TrackingCalendarFeaturesEventDialog: typeof import('./../src/components/tracking/calendar/features/EventDialog.vue')['default']
    TrackingCalendarSidebar: typeof import('./../src/components/tracking/calendar/Sidebar.vue')['default']
    TrackingCalendarView: typeof import('./../src/components/tracking/calendar/View.vue')['default']
  }
}
